/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedElectricityRouteImport } from './routes/_authenticated/electricity'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated/data'
import { Route as AuthenticatedCableRouteImport } from './routes/_authenticated/cable'
import { Route as AuthenticatedAirtimeToCashRouteImport } from './routes/_authenticated/airtime-to-cash'
import { Route as AuthenticatedAirtimeRouteImport } from './routes/_authenticated/airtime'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedElectricityRoute =
  AuthenticatedElectricityRouteImport.update({
    id: '/_authenticated/electricity',
    path: '/electricity',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/_authenticated/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/_authenticated/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCableRoute = AuthenticatedCableRouteImport.update({
  id: '/_authenticated/cable',
  path: '/cable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAirtimeToCashRoute =
  AuthenticatedAirtimeToCashRouteImport.update({
    id: '/_authenticated/airtime-to-cash',
    path: '/airtime-to-cash',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAirtimeRoute = AuthenticatedAirtimeRouteImport.update({
  id: '/_authenticated/airtime',
  path: '/airtime',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/airtime': typeof AuthenticatedAirtimeRoute
  '/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/cable': typeof AuthenticatedCableRoute
  '/data': typeof AuthenticatedDataRoute
  '/education': typeof AuthenticatedEducationRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/airtime': typeof AuthenticatedAirtimeRoute
  '/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/cable': typeof AuthenticatedCableRoute
  '/data': typeof AuthenticatedDataRoute
  '/education': typeof AuthenticatedEducationRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/airtime': typeof AuthenticatedAirtimeRoute
  '/_authenticated/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/_authenticated/cable': typeof AuthenticatedCableRoute
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/electricity': typeof AuthenticatedElectricityRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/airtime'
    | '/airtime-to-cash'
    | '/cable'
    | '/data'
    | '/education'
    | '/electricity'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/airtime'
    | '/airtime-to-cash'
    | '/cable'
    | '/data'
    | '/education'
    | '/electricity'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/airtime'
    | '/_authenticated/airtime-to-cash'
    | '/_authenticated/cable'
    | '/_authenticated/data'
    | '/_authenticated/education'
    | '/_authenticated/electricity'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAirtimeRoute: typeof AuthenticatedAirtimeRoute
  AuthenticatedAirtimeToCashRoute: typeof AuthenticatedAirtimeToCashRoute
  AuthenticatedCableRoute: typeof AuthenticatedCableRoute
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedElectricityRoute: typeof AuthenticatedElectricityRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/electricity': {
      id: '/_authenticated/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof AuthenticatedElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cable': {
      id: '/_authenticated/cable'
      path: '/cable'
      fullPath: '/cable'
      preLoaderRoute: typeof AuthenticatedCableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/airtime-to-cash': {
      id: '/_authenticated/airtime-to-cash'
      path: '/airtime-to-cash'
      fullPath: '/airtime-to-cash'
      preLoaderRoute: typeof AuthenticatedAirtimeToCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/airtime': {
      id: '/_authenticated/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AuthenticatedAirtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAirtimeRoute: AuthenticatedAirtimeRoute,
  AuthenticatedAirtimeToCashRoute: AuthenticatedAirtimeToCashRoute,
  AuthenticatedCableRoute: AuthenticatedCableRoute,
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedElectricityRoute: AuthenticatedElectricityRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
