/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedElectricityRouteImport } from './routes/_authenticated/electricity'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated/data'
import { Route as AuthenticatedCreatePinRouteImport } from './routes/_authenticated/create-pin'
import { Route as AuthenticatedCableRouteImport } from './routes/_authenticated/cable'
import { Route as AuthenticatedAirtimeToCashRouteImport } from './routes/_authenticated/airtime-to-cash'
import { Route as AuthenticatedAirtimeRouteImport } from './routes/_authenticated/airtime'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as ApiPublicWebhooksOtapayA2cRouteImport } from './routes/api/public/webhooks/otapay-a2c'
import { Route as ApiPublicHooksOtapaySyncRouteImport } from './routes/api/public/hooks/otapay-sync'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElectricityRoute =
  AuthenticatedElectricityRouteImport.update({
    id: '/electricity',
    path: '/electricity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatePinRoute = AuthenticatedCreatePinRouteImport.update({
  id: '/create-pin',
  path: '/create-pin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCableRoute = AuthenticatedCableRouteImport.update({
  id: '/cable',
  path: '/cable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAirtimeToCashRoute =
  AuthenticatedAirtimeToCashRouteImport.update({
    id: '/airtime-to-cash',
    path: '/airtime-to-cash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAirtimeRoute = AuthenticatedAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksOtapayA2cRoute =
  ApiPublicWebhooksOtapayA2cRouteImport.update({
    id: '/api/public/webhooks/otapay-a2c',
    path: '/api/public/webhooks/otapay-a2c',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOtapaySyncRoute =
  ApiPublicHooksOtapaySyncRouteImport.update({
    id: '/api/public/hooks/otapay-sync',
    path: '/api/public/hooks/otapay-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/airtime': typeof AuthenticatedAirtimeRoute
  '/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/cable': typeof AuthenticatedCableRoute
  '/create-pin': typeof AuthenticatedCreatePinRoute
  '/data': typeof AuthenticatedDataRoute
  '/education': typeof AuthenticatedEducationRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/public/hooks/otapay-sync': typeof ApiPublicHooksOtapaySyncRoute
  '/api/public/webhooks/otapay-a2c': typeof ApiPublicWebhooksOtapayA2cRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/airtime': typeof AuthenticatedAirtimeRoute
  '/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/cable': typeof AuthenticatedCableRoute
  '/create-pin': typeof AuthenticatedCreatePinRoute
  '/data': typeof AuthenticatedDataRoute
  '/education': typeof AuthenticatedEducationRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/otapay-sync': typeof ApiPublicHooksOtapaySyncRoute
  '/api/public/webhooks/otapay-a2c': typeof ApiPublicWebhooksOtapayA2cRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/airtime': typeof AuthenticatedAirtimeRoute
  '/_authenticated/airtime-to-cash': typeof AuthenticatedAirtimeToCashRoute
  '/_authenticated/cable': typeof AuthenticatedCableRoute
  '/_authenticated/create-pin': typeof AuthenticatedCreatePinRoute
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/electricity': typeof AuthenticatedElectricityRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/otapay-sync': typeof ApiPublicHooksOtapaySyncRoute
  '/api/public/webhooks/otapay-a2c': typeof ApiPublicWebhooksOtapayA2cRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/airtime'
    | '/airtime-to-cash'
    | '/cable'
    | '/create-pin'
    | '/data'
    | '/education'
    | '/electricity'
    | '/history'
    | '/profile'
    | '/api/public/hooks/otapay-sync'
    | '/api/public/webhooks/otapay-a2c'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/airtime'
    | '/airtime-to-cash'
    | '/cable'
    | '/create-pin'
    | '/data'
    | '/education'
    | '/electricity'
    | '/history'
    | '/profile'
    | '/'
    | '/api/public/hooks/otapay-sync'
    | '/api/public/webhooks/otapay-a2c'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/airtime'
    | '/_authenticated/airtime-to-cash'
    | '/_authenticated/cable'
    | '/_authenticated/create-pin'
    | '/_authenticated/data'
    | '/_authenticated/education'
    | '/_authenticated/electricity'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/api/public/hooks/otapay-sync'
    | '/api/public/webhooks/otapay-a2c'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksOtapaySyncRoute: typeof ApiPublicHooksOtapaySyncRoute
  ApiPublicWebhooksOtapayA2cRoute: typeof ApiPublicWebhooksOtapayA2cRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/electricity': {
      id: '/_authenticated/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof AuthenticatedElectricityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-pin': {
      id: '/_authenticated/create-pin'
      path: '/create-pin'
      fullPath: '/create-pin'
      preLoaderRoute: typeof AuthenticatedCreatePinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cable': {
      id: '/_authenticated/cable'
      path: '/cable'
      fullPath: '/cable'
      preLoaderRoute: typeof AuthenticatedCableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/airtime-to-cash': {
      id: '/_authenticated/airtime-to-cash'
      path: '/airtime-to-cash'
      fullPath: '/airtime-to-cash'
      preLoaderRoute: typeof AuthenticatedAirtimeToCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/airtime': {
      id: '/_authenticated/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AuthenticatedAirtimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/otapay-a2c': {
      id: '/api/public/webhooks/otapay-a2c'
      path: '/api/public/webhooks/otapay-a2c'
      fullPath: '/api/public/webhooks/otapay-a2c'
      preLoaderRoute: typeof ApiPublicWebhooksOtapayA2cRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/otapay-sync': {
      id: '/api/public/hooks/otapay-sync'
      path: '/api/public/hooks/otapay-sync'
      fullPath: '/api/public/hooks/otapay-sync'
      preLoaderRoute: typeof ApiPublicHooksOtapaySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAirtimeRoute: typeof AuthenticatedAirtimeRoute
  AuthenticatedAirtimeToCashRoute: typeof AuthenticatedAirtimeToCashRoute
  AuthenticatedCableRoute: typeof AuthenticatedCableRoute
  AuthenticatedCreatePinRoute: typeof AuthenticatedCreatePinRoute
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedElectricityRoute: typeof AuthenticatedElectricityRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAirtimeRoute: AuthenticatedAirtimeRoute,
  AuthenticatedAirtimeToCashRoute: AuthenticatedAirtimeToCashRoute,
  AuthenticatedCableRoute: AuthenticatedCableRoute,
  AuthenticatedCreatePinRoute: AuthenticatedCreatePinRoute,
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedElectricityRoute: AuthenticatedElectricityRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksOtapaySyncRoute: ApiPublicHooksOtapaySyncRoute,
  ApiPublicWebhooksOtapayA2cRoute: ApiPublicWebhooksOtapayA2cRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
